name: Cut a release

on: 
  workflow_dispatch

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set committer info
        run: |
          git config --local user.email "${{ secrets.BOT_EMAIL }}"
          git config --local user.name "Vue Styleguidist Bot"

      - name: Checkout dev branch
        run: git checkout dev

      - name: Check for merge conflict
        id: check-conflict
        run: echo "::set-output name=merge_conflict::$(git merge-tree $(git merge-base HEAD delivery) delivery HEAD | egrep '<<<<<<<')"
        
      - name: Failed merge, set merged status as failed
        run: echo "::set-output name=merge_conflict::'failed merge'"
        if: ${{ steps.merge-master.outcome != 'success' }}

      - name: Merge delivery into dev
        id: merge-delivery
        run: git merge delivery
        if: ${{ !steps.check-conflict.outputs.merge_conflict }}
        
      - name: Push
        run: git push
        if: ${{ !steps.check-conflict.outputs.merge_conflict }}
      